update

diff --git a/cctools-repo/misc/sdktools/aproject b/cctools-repo/misc/sdktools/aproject
--- a/cctools-repo/misc/sdktools/aproject
+++ b/cctools-repo/misc/sdktools/aproject
@@ -13,17 +13,88 @@ error() {
     exit 1
 }
 
-if [ "$1" = "init" -a "$2" = "project" ]; then
-    PROJECT_PATH="$3"
-    PROJECT_PACKAGE=$4
-    PROJECT_NAME=$5
-    PROJECT_APPNAME="$6"
+usage_create() {
+    echo
+    echo "Options for create:"
+    echo "-n --name                    - Project name. [required]"
+    echo "-t --target                  - Target ID of the new project."
+    echo "-p --path                    - The new project's directory. [required]"
+    echo "-k --package                 - Android package name. [required]"
+    echo "-a --activity                - Name of the default Activity that is created."
+    echo "                               [required for application project]"
+    echo "-N --appname                 - Application name. [application project only]"
+    echo
+    
+    exit 1
+}
+
+usage() {
+    echo
+    echo "Usage:"
+    echo "create project [options]     - Creates a new Android project."
+    echo "create lib-project [options] - Creates a new Android library project."
+    echo "build [debug]                - Build a project."
+    echo "build relese                 - Build a release project."
+    echo "clean                        - Clean a project files."
+
+    usage_create
+}
+
+if [ "$1" = "create" ]; then
+    PROJECT_LIBRARY=
+    if [ "$2" = "lib-project" ]; then
+	PROJECT_LIBRARY="yes"
+    elif [ ! "$2" = "project" ]; then
+	usage
+    fi
+
+    shift 2
+
+    O=`getopt -n aproject -l path:,package:,activity:,name:,appname:,target: -o p:k:a:n:N:t: -- "$@"` || exit 1
+    eval set -- "$O"
+    while true; do
+	case "$1" in
+	-p|--path)
+	    PROJECT_PATH="$2"; shift 2;;
+	-k|--package)
+	    PROJECT_PACKAGE="$2"; shift 2;;
+	-a|--activity)
+	    PROJECT_ACTIVITY="$2";shift 2;;
+	-n|--name)
+	    PROJECT_NAME="$2"; shift 2;;
+	-N|--appname)
+	    PROJECT_APPNAME="$2"; shift 2;;
+	-t|--target)
+	    PROJECT_TARGET="$2"; shift 2;;
+	--)
+	    shift; break;;
+	*)
+	    echo Error; exit 1;;
+	esac
+    done
+
+    if [ ! "$@" = "" ]; then
+	echo "aproject: unrecognized options: $@"
+	usage_create
+    fi
+
+    if [ "$PROJECT_PATH" = "" -o "$PROJECT_PACKAGE" = "" -o "$PROJECT_NAME" = "" ]; then
+	usage_create
+    fi
+
+    if [ "$PROJECT_LIBRARY" = "" -a "$PROJECT_ACTIVITY" = "" ]; then
+	usage_create
+    fi
 
     if [ "$PROJECT_APPNAME" = "" ]; then
 	PROJECT_APPNAME=$PROJECT_NAME
     fi
 
-    ANDROID_SDK_VER=`getprop ro.build.version.sdk`
+    if [ "$PROJECT_TARGET" = "" ]; then
+	ANDROID_SDK_VER=`getprop ro.build.version.sdk`
+    else
+	ANDROID_SDK_VER=$PROJECT_TARGET
+    fi
     ANDROID_SDK=${CCTOOLSDIR}/sdk/android-${ANDROID_SDK_VER}
 
     if [ ! -d $ANDROID_SDK ]; then
@@ -40,17 +111,25 @@ if [ "$1" = "init" -a "$2" = "project" ]; then
 
     mkdir -p $p1
     cp -f ${ANDROID_SDK}/template/AndroidManifest.template ${p}/AndroidManifest.xml
-    cp -f ${ANDROID_SDK}/template/java_file.template       ${p1}/${PROJECT_NAME}.java
     cp -f ${ANDROID_SDK}/template/layout.template          ${p}/res/layout/main.xml
     cp -f ${ANDROID_SDK}/template/strings.template         ${p}/res/values/strings.xml
     cp -f ${ANDROID_SDK}/template/ic_launcher_ldpi.png     ${p}/res/drawable-ldpi/ic_launcher.png
     cp -f ${ANDROID_SDK}/template/ic_launcher_mdpi.png     ${p}/res/drawable-mdpi/ic_launcher.png
     cp -f ${ANDROID_SDK}/template/ic_launcher_hdpi.png     ${p}/res/drawable-hdpi/ic_launcher.png
 
+    if [ "$PROJECT_LIBRARY" = "yes" ]; then
+    cp -f ${ANDROID_SDK}/template/java_file.template       ${p1}/${PROJECT_NAME}.java
     sed -i -e "s|PACKAGE|$PROJECT_PACKAGE|" \
            -e "s|ACTIVITY_ENTRY_NAME|$PROJECT_NAME|" \
            -e "s|ACTIVITY_CLASS_NAME|$PROJECT_NAME|" \
            -e "s|ICON|android:icon=\"@drawable/ic_launcher\"|" ${p}/AndroidManifest.xml ${p1}/${PROJECT_NAME}.java
+    else
+    cp -f ${ANDROID_SDK}/template/java_file.template       ${p1}/${PROJECT_ACTIVITY}.java
+    sed -i -e "s|PACKAGE|$PROJECT_PACKAGE|" \
+           -e "s|ACTIVITY_ENTRY_NAME|$PROJECT_ACTIVITY|" \
+           -e "s|ACTIVITY_CLASS_NAME|$PROJECT_ACTIVITY|" \
+           -e "s|ICON|android:icon=\"@drawable/ic_launcher\"|" ${p}/AndroidManifest.xml ${p1}/${PROJECT_ACTIVITY}.java
+    fi
 
     sed -i -e "s|PACKAGE|$PROJECT_PACKAGE|" \
            -e "s|ACTIVITY_ENTRY_NAME|$PROJECT_APPNAME|" \
@@ -58,6 +137,18 @@ if [ "$1" = "init" -a "$2" = "project" ]; then
            -e "s|ICON|android:icon=\"@drawable/ic_launcher\"|" ${p}/res/layout/main.xml ${p}/res/values/strings.xml
 
     sed -i -e "s|<application|<uses-sdk android:targetSdkVersion=\"$ANDROID_SDK_VER\" />\n    <application|" ${p}/AndroidManifest.xml
+
+cat > ${p}/project.properties << EOF
+# This file is automatically generated by aproject.
+
+target=android-${ANDROID_SDK_VER}
+EOF
+
+    if [ "$PROJECT_LIBRARY" = "yes" ]; then
+
+	echo "android.library=true" >> ${p}/project.properties
+
+    fi
 
     exit 0
 fi
@@ -80,12 +171,14 @@ is_library() {
     done
 }
 
-if [ ! -f AndroidManifest.xml ]; then
-    echo "Not android project directory!"
-    exit 1
-fi
+check_android_manifest() {
+    if [ ! -f AndroidManifest.xml ]; then
+	echo "Not android project directory!"
+	exit 1
+    fi
+}
 
-PROJECTNAME=`aproject-helper AppName`
+PROJECTNAME=`aproject-helper AppName 2>/dev/null`
 if [ "$PROJECTNAME" = "" ]; then
     PROJECTNAME=`basename $TOPDIR`
 fi
@@ -108,6 +201,7 @@ if [ "$1" = "-v" ]; then
 fi
 
 if [ "$1" = "clean" ]; then
+    check_android_manifest
     echo "Cleaning $PROJECTNAME"
     rm -rf bin gen
     for d in `get_ext_libdirs`; do
@@ -117,9 +211,17 @@ if [ "$1" = "clean" ]; then
     exit 0
 fi
 
+if [ ! "$1" = "build" ]; then
+    usage
+fi
+
+shift
+
+check_android_manifest
+
 for d in `get_ext_libdirs`; do
     cd $d
-    $APROJECT_BIN $VERBOSE_AAPT $@ || error "external library"
+    $APROJECT_BIN $VERBOSE_AAPT build $@ || error "external library"
     cd $TOPDIR
 done
 
@@ -186,7 +288,7 @@ find_libs_for_dex() {
 get_ext_resources() {
     local d
     for d in $@; do
-	printf "-S ${d}/bin/res -S ${d}/res"
+	printf "-S ${d}/bin/res -S ${d}/res "
     done
 }
 
@@ -219,7 +321,7 @@ fi
 
 echo "Starting aapt..."
 
-if [ "$ACTIVITIES" = "" ]; then
+if [ "$IS_LIBRARY" = "true" -o "$ACTIVITIES" = "" ]; then
     aapt p \
 	--non-constant-id \
 	-f $VERBOSE_AAPT \
