gui messages, default sdk is 19

diff --git a/cctools-repo/misc/sdktools/aproject b/cctools-repo/misc/sdktools/aproject
--- a/cctools-repo/misc/sdktools/aproject
+++ b/cctools-repo/misc/sdktools/aproject
@@ -50,7 +50,8 @@ if [ "$1" = "create" ]; then
 
     shift 2
 
-    O=`getopt -n aproject -l path:,package:,activity:,name:,appname:,target: -o p:k:a:n:N:t: -- "$@"` || exit 1
+    USE_GUIBOX=
+    O=`getopt -n aproject -l path:,package:,activity:,name:,appname:,target:,gui -o p:k:a:n:N:t:g -- "$@"` || exit 1
     eval set -- "$O"
     while true; do
 	case "$1" in
@@ -66,6 +67,8 @@ if [ "$1" = "create" ]; then
 	    PROJECT_APPNAME="$2"; shift 2;;
 	-t|--target)
 	    PROJECT_TARGET="$2"; shift 2;;
+	-g|--gui)
+	    USE_GUIBOX=yes; shift;;
 	--)
 	    shift; break;;
 	*)
@@ -79,11 +82,21 @@ if [ "$1" = "create" ]; then
     fi
 
     if [ "$PROJECT_PATH" = "" -o "$PROJECT_PACKAGE" = "" -o "$PROJECT_NAME" = "" ]; then
-	usage_create
+	if [ "$USE_GUIBOX" = "yes" ]; then
+	    adialog --msgbox --title "Error!" --message "Cannot create a project" --text "Check project path, package or name."
+	    exit 1
+	else
+	    usage_create
+	fi
     fi
 
     if [ "$PROJECT_LIBRARY" = "" -a "$PROJECT_ACTIVITY" = "" ]; then
-	usage_create
+	if [ "$USE_GUIBOX" = "yes" ]; then
+	    adialog --msgbox --title "Error!" --message "Cannot create a project" --text "Empty activity name."
+	    exit 1
+	else
+	    usage_create
+	fi
     fi
 
     if [ "$PROJECT_APPNAME" = "" ]; then
@@ -98,8 +111,17 @@ if [ "$1" = "create" ]; then
     ANDROID_SDK=${CCTOOLSDIR}/sdk/android-${ANDROID_SDK_VER}
 
     if [ ! -d $ANDROID_SDK ]; then
-	echo "ERROR: No SDK Android-${ANDROID_SDK_VER} found!"
-	exit 1
+	ANDROID_SDK=${CCTOOLSDIR}/sdk/android-19
+    fi
+
+    if [ ! -d $ANDROID_SDK ]; then
+	if [ "$USE_GUIBOX" = "yes" ]; then
+	    adialog --msgbox --title "Error!" --message "Cannot create a project" --text "No SDK Android-${ANDROID_SDK_VER} found."
+	    exit 1
+	else
+	    echo "ERROR: No SDK Android-${ANDROID_SDK_VER} found!"
+	    exit 1
+	fi
     fi
 
     p="${PROJECT_PATH}/${PROJECT_NAME}"
@@ -150,6 +172,9 @@ EOF
 
     fi
 
+    if [ "$USE_GUIBOX" = "yes" ]; then
+	adialog --msgbox --title "Congratulation!" --message "New project created!" --text "Project path is ${p}."
+    fi
     exit 0
 fi
 
